name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Setup .NET environment (adjust dotnet-version if needed)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Build the solution
      - name: Build
        run: dotnet build --configuration Debug --no-restore
      
      # Run tests
      - name: Run tests
        run: dotnet test --configuration Debug --no-build --verbosity normal
